# Generated by Django 5.2 on 2025-09-17 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('variedad', models.CharField(max_length=100, verbose_name='Variedad')),
                ('tipo', models.CharField(choices=[('cereales', 'Cereales'), ('hortalizas', 'Hortalizas'), ('frutales', 'Frutales'), ('legumbres', 'Legumbres'), ('tubérculos', 'Tubérculos'), ('oleaginosas', 'Oleaginosas'), ('forrajes', 'Forrajes'), ('otros', 'Otros')], max_length=20, verbose_name='Tipo')),
                ('ciclo_dias', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Ciclo en días')),
                ('rendimiento_esperado', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rendimiento esperado (kg/ha)')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('temperatura_optima_min', models.FloatField(blank=True, null=True, verbose_name='Temperatura óptima mínima (°C)')),
                ('temperatura_optima_max', models.FloatField(blank=True, null=True, verbose_name='Temperatura óptima máxima (°C)')),
                ('ph_suelo_min', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)], verbose_name='pH mínimo del suelo')),
                ('ph_suelo_max', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)], verbose_name='pH máximo del suelo')),
                ('precipitacion_anual', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precipitación anual requerida (mm)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Cultivo',
                'verbose_name_plural': 'Cultivos',
                'ordering': ['nombre'],
            },
        ),
    ]
