# Generated by Django 5.2 on 2025-09-17 16:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('area_hectareas', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Área (hectáreas)')),
                ('ubicacion_lat', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitud')),
                ('ubicacion_lng', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitud')),
                ('altitud', models.FloatField(blank=True, null=True, verbose_name='Altitud (msnm)')),
                ('tipo_suelo', models.CharField(blank=True, choices=[('arcilloso', 'Arcilloso'), ('arenoso', 'Arenoso'), ('franco', 'Franco'), ('franco_arcilloso', 'Franco Arcilloso'), ('franco_arenoso', 'Franco Arenoso'), ('limoso', 'Limoso'), ('franco_limoso', 'Franco Limoso'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Tipo de suelo')),
                ('ph_suelo', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)], verbose_name='pH del suelo')),
                ('materia_organica', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Materia orgánica (%)')),
                ('capacidad_campo', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Capacidad de campo (%)')),
                ('fecha_siembra', models.DateField(blank=True, null=True, verbose_name='Fecha de siembra')),
                ('fecha_cosecha_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha estimada de cosecha')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('sembrada', 'Sembrada'), ('en_crecimiento', 'En Crecimiento'), ('lista_cosecha', 'Lista para Cosecha'), ('cosechada', 'Cosechada'), ('en_descanso', 'En Descanso'), ('mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20, verbose_name='Estado')),
                ('tiene_riego', models.BooleanField(default=False, verbose_name='Tiene sistema de riego')),
                ('tipo_riego', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de riego')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('cultivo_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas_actuales', to='cultivos.cultivo', verbose_name='Cultivo actual')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='HistorialParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_siembra', models.DateField(verbose_name='Fecha de siembra')),
                ('fecha_cosecha', models.DateField(blank=True, null=True, verbose_name='Fecha de cosecha')),
                ('rendimiento_obtenido', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rendimiento obtenido (kg/ha)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo', verbose_name='Cultivo')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='parcelas.parcela', verbose_name='Parcela')),
            ],
            options={
                'verbose_name': 'Historial de Parcela',
                'verbose_name_plural': 'Historiales de Parcelas',
                'ordering': ['-fecha_siembra'],
            },
        ),
        migrations.AddIndex(
            model_name='parcela',
            index=models.Index(fields=['codigo'], name='parcelas_pa_codigo_982c04_idx'),
        ),
        migrations.AddIndex(
            model_name='parcela',
            index=models.Index(fields=['estado'], name='parcelas_pa_estado_0130d9_idx'),
        ),
        migrations.AddIndex(
            model_name='parcela',
            index=models.Index(fields=['cultivo_actual'], name='parcelas_pa_cultivo_e2c1f0_idx'),
        ),
    ]
